### PR TITLE
support mTLS for Zookeeper Native Client

### PR DESCRIPTION
**Pull request by HessTina-YuI**

### CODE REVIEW

**Comment by haoel** [comment]
@HessTina-YuI thanks for this contribution. However, this PR hasn't implemented the mTLS connection for zookeeper. 

please take a look [this zookeeper document](https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide) to set up your environment

And the following issue could help you finish your code.
https://github.com/samuel/go-zookeeper/issues/161

**Comment by HessTina-YuI** [comment]
Thx @haoel , I will do it.

**Comment by HessTina-YuI** [comment]
Hi @haoel , I support mTLS in zookeeper.

**Review by haoel — APPROVED** [review]
LGTM！

**Pull request merged**
