### PR TITLE
chore: add arm64 support for docker image

### PR DESCRIPTION
**Pull request by gelleson**
Add support of arm to docker images

### CODE REVIEW

**Comment by haoel** [comment]
Thank for this PR @gelleson 

But I don't think it works. I think you need to use the docker manifest. 
You can take a look at this: https://goreleaser.com/customization/docker_manifest/

**Comment by gelleson** [comment]
You are right! Thanks. I will try to rework my PR.

**Comment by haoel** [comment]
Just a couple of hints:

1) For `.goreleaser.yaml` we need to do these changes:
- use docker buildx
- add the `--platform=linux/arm64/v8` as docker build parameters
- add the `docker_manifest` section

2) For  `Dockerfile.goreleaser` we need to deal with the platform. 
- add the `--platform=$BUILDPLATFORM` for `FROM alpine:latest`

**Comment by gelleson** [comment]
Good point. Later I will try to update my PR.

**Comment by haoel** [comment]
Due to this PR is aged, support arm64 docker image in #50

**Pull request closed without merging**
