### PR TITLE
Support the multiple YAML files

### PR DESCRIPTION
**Pull request by yafengstark**
#201 
I add some code to support the multiple YAML files. Now you can use multiple `-f` to split configuration. 
I am a new Golang user. Please review the code carefully.
Thanks.

### CODE REVIEW

**Comment by haoel** [comment]
@yafengstark thanks so much for this PR. and sorry for the delayed response.

I appreciate your work. And I think we should design this carefully before we start to code. 

the following things we need to think about:

1) if there has some configuration conflict, how to solve the conflict? 
2) do you think we can just simply concatenate all of the yaml files to a single yaml file, then we can keep the rest thing with no change?
3) if 2) is the better solution, why not just use a shell helper script to merge the multiple yaml files to a single yaml? 

Overall, actually, this problem is how to manage the EaseProbe's configuration, I think we can do this outside of EaseProbe and keep EaseProbe simple and stupid.

**Comment by yafengstark** [comment]
> 

@haoel thanks for your reply. Sorry for the delayed response.

You point out the key. I agree with you that we should do this outside of EaseProbe.

I find the repository [https://github.com/herrjulz/aviator](aviator).The repository  specifies the path to the base YAML file. All other YAML files will be merged on top of this YAML file.

I do some simple tests, it works.
But I do not kown When some configuration conflict will occur, so I do not test the conflict.

What do you think of this repository？If there is anything to be done, I can do some work.

thanks.

**Comment by haoel** [comment]
the `aviator` looks not bad.  we probably can introduce the `conf.d` for the pieces of yaml files, and the original `config.yaml` is the base yaml.

**Comment by haoel** [comment]
This PR has been addressed by PR #218

**Pull request closed without merging**
