### PR TITLE
Make linger configurable

### PR DESCRIPTION
**Pull request by proditis**
The following PR is an attempt to make SO_LINGER option configurable. 

It introduces a new `bool` option named `nolinger` for tcp, tls, http and ssh probes which disables `SO_LINGER`. Default value set to `false` to match the previous easeprobe operation and not require configuration changes when updated.

Documentation also updated to include the addition of this option.

Notes:
* Needs testing (i am unable to test it currently)
* I dont know how to implement the new option for our test cases.

### CODE REVIEW

**Review by samanhappy — APPROVED** [review]
LGTM

**Comment by suchen-sci** [comment]
Hi @proditis, 

Thank you for your pull request. However, there is a concern with this change. Prior to this PR, the default behavior was equivalent to setting `linger` to `true`. Although you've used `jsonschema` to set the default value of `linger` to `true`, this doesn't actually work in this case because we're using `yaml.Unmarshal` for loading, which doesn't enforce those defaults.

To maintain the previous default behavior, I strongly recommend using `nolinger` instead of `linger`. This would ensure that the behavior remains consistent.

**Review by suchen-sci — COMMENTED** [review]
Hi @proditis,

Thank you for your pull request. However, there is a concern with this change. Prior to this PR, the default behavior was equivalent to setting `linger` to `true`. Although you've used `jsonschema` to set the default value of `linger` to true, this doesn't actually work in this case because we're using `yaml.Unmarshal` for loading, which doesn't enforce those defaults.

To maintain the previous default behavior, I strongly recommend using `nolinger` instead of `linger`. This would ensure that the behavior remains consistent.

**Review by suchen-sci — APPROVED** [review]

**Comment by Mr-YYM** [comment]
when to release a new version? 😄

**Comment by suchen-sci** [comment]
@Mr-YYM There is a new PR in progress, if that one is merged. We will release a new version.

**Pull request merged**
