### PR TITLE
Versionizing the binary, config, data file

### LINKED ISSUE #98: Add version option for executable and configuration files
**Background & X Problem**
I wanted to performing updates between v1.4.0 and the latest version from repo on my systems, as part of the process I wanted to confirm the version of the binary but we currently have no command line option that will simply display the version. 
As it currently stands those who are interested in tracking the version somehow, have to go through checksums to the binary which is not optimal imho.

Similarly I could not determine for what version of binary my config was for.

**Proposal and Expectation**
I propose the following, 

* addition of a command line option `-v` or `-V` that will just display the version of the current binary
* addition of the version string to the displayed `Usage`
* addition of a `config.yaml` top key `version:` that will allow us to determine what version of binary this config works with
* (optionally) include a `version` key also on the `data.yaml` so that future binaries can detect older versions of the data and accommodate any potential changes that need to take place

_edit: If anyone wants to take on this please be my guest_

### PR DESCRIPTION
**Pull request by haoel**
fixes #98 

- [x] easeprobe -v
```shell
$ ./easeprobe -v                                                                                                                                  ─╯
EaseProbe v1.5.0
```
- [x] easeprobe -h

```shell
$ ./easeprobe -h                                                                                                                                  ─╯
Usage of build/bin/easeprobe:
  -d    dry notification mode
  -f string
        configuration file (default "config.yaml")
  -v    prints version
```

- [x] config.yaml

```yaml
version : 1.5.0
```

- [x] data.yaml 

```yaml
---
name: EaseProbe
version: v1.5.0
---
Probe:
   ...
  ....
```

### CODE REVIEW

**Comment by proditis** [comment]
@haoel Should I be able to see the version metadata inside `data.yaml` ? There was no version information inside.

**Review by proditis — APPROVED** [review]
LGTM

**Comment by haoel** [comment]
supplying the unit tests for the data file.

**Comment by haoel** [comment]
Originally, we use the RFC3339  time format as the data file backup file name,  on the Windows platform, it is invalid, because it includes `:`,  in the latest commit, we replace the  `:` with `_` to fix this problem.

**Comment by proditis** [comment]
I think that this was the error i also came across. Wow NICE CATCH :clap:

**Comment by haoel** [comment]
> @haoel Should I be able to see the version metadata inside `data.yaml` ? There was no version information inside.
> 
> 

Yes. 

If the original data.yaml hasn't version data. The new program would write it.

**Comment by proditis** [comment]
@haoel I have tested your pr and when the data.yaml do not exist the meta data are like so
```yaml
---
name: ""
version: ""
---
```

When the file exists and the rotation takes place the new data.yaml has indeed meta information like so
```yaml
---
name: EaseProbe
version: v1.5.0
---
```

I tried track this down but i couldn't, i hope these details help in tracking the case with the empty strings.

**Comment by haoel** [comment]
@proditis  Good catch! I fixed this issue, and add the unit test case in `TestMetaData()` .

**Review by proditis — APPROVED** [review]
everything works as advertised :ok_hand:

**Pull request merged**
