### PR TITLE
feat: support go1.21 build

### PR DESCRIPTION
**Pull request by chenrui333**
Right now, there is some go.sum discrepancies with go1.21 build, run `go mod tidy` with go1.21.6 to support go1.21 build.

- relates to https://github.com/Homebrew/homebrew-core/pull/159493

### CODE REVIEW

**Comment by chenrui333** [comment]
this is very similar to kubecm pr, https://github.com/sunny0826/kubecm/pull/847

**Comment by samanhappy** [comment]
@chenrui333 there is a failed test [here](https://github.com/megaease/easeprobe/actions/runs/7478173978/job/20369876679?pr=471#step:5:775) with the following logs:
```
=== RUN   TestMemcache
    memcache_test.go:48: 
        	Error Trace:	D:/a/easeprobe/easeprobe/probe/client/memcache/memcache_test.go:48
        	Error:      	"dial tcp 127.0.0.1:12345: connectex: No connection could be made because the target machine actively refused it." does not contain "connect timeout"
        	Test:       	TestMemcache
--- FAIL: TestMemcache (0.02s)
```
please help to check if it's caused by these changes or if the test code needs optimization to align?

**Comment by chenrui333** [comment]
@samanhappy I guess we can do a quick rerun to see if it is reproducible, looks like only failed with windows build.

**Comment by samanhappy** [comment]
@chenrui333 it's reproducible and seems to be caused by some low-level implementation in go 1.21 on Windows, you can fix it like what I did [here](https://github.com/samanhappy/easeprobe/pull/6/commits/34d496715bca0779199b593b5e63342d65019d94).

**Comment by chenrui333** [comment]
yeah, let me give a try later, thanks!

**Comment by suchen-sci** [comment]
Hi, @chenrui333 could you please fix it? We'd like to update easeprobe to golang 1.21.

**Comment by suchen-sci** [comment]
we are now in go 1.21, so i will close this pr.

**Pull request closed without merging**
